POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Veterinario",
  "email": "veterinario@gmail.com",
  "password": "veterinario"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Cliente",
  "email": "cliente@gmail.com",
  "password": "cliente"
}
